<?php

########################################################################
# Extension Manager/Repository config file for ext: "in2help"
#
# Auto generated by Extension Builder 2012-07-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Online-Documentation',
    'description' => 'Provides the help for pages and contentelements with design patterns',
    'category' => 'module',
    'author' => 'Martin Huber',
    'author_email' => 'martin.huber@in2code.de',
    'author_company' => 'in2code GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '2.0.0',
    'constraints' => array(
        'depends' => array(
            'extbase' => '1.4',
            'fluid' => '1.4',
            'typo3' => '7.6-',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);

?>
